// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/form/v1/form.proto

package formv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateFormDefinitionRequest 创建表单定义请求
type CreateFormDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Schema        string                 `protobuf:"bytes,6,opt,name=schema,proto3" json:"schema,omitempty"`                     // JSON schema
	UiSchema      string                 `protobuf:"bytes,7,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"` // UI schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormDefinitionRequest) Reset() {
	*x = CreateFormDefinitionRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormDefinitionRequest) ProtoMessage() {}

func (x *CreateFormDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateFormDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFormDefinitionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateFormDefinitionRequest) GetUiSchema() string {
	if x != nil {
		return x.UiSchema
	}
	return ""
}

// GetFormDefinitionRequest 获取表单定义请求
type GetFormDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormDefinitionRequest) Reset() {
	*x = GetFormDefinitionRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormDefinitionRequest) ProtoMessage() {}

func (x *GetFormDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetFormDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{1}
}

func (x *GetFormDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateFormDefinitionRequest 更新表单定义请求
type UpdateFormDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Schema        string                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	UiSchema      string                 `protobuf:"bytes,5,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormDefinitionRequest) Reset() {
	*x = UpdateFormDefinitionRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormDefinitionRequest) ProtoMessage() {}

func (x *UpdateFormDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFormDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFormDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFormDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFormDefinitionRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *UpdateFormDefinitionRequest) GetUiSchema() string {
	if x != nil {
		return x.UiSchema
	}
	return ""
}

// DeleteFormDefinitionRequest 删除表单定义请求
type DeleteFormDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormDefinitionRequest) Reset() {
	*x = DeleteFormDefinitionRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormDefinitionRequest) ProtoMessage() {}

func (x *DeleteFormDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFormDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListFormDefinitionsRequest 列出表单定义请求
type ListFormDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormDefinitionsRequest) Reset() {
	*x = ListFormDefinitionsRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormDefinitionsRequest) ProtoMessage() {}

func (x *ListFormDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListFormDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{4}
}

func (x *ListFormDefinitionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListFormDefinitionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFormDefinitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// FormDefinitionResponse 表单定义响应
type FormDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Schema        string                 `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	UiSchema      string                 `protobuf:"bytes,8,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormDefinitionResponse) Reset() {
	*x = FormDefinitionResponse{}
	mi := &file_api_form_v1_form_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDefinitionResponse) ProtoMessage() {}

func (x *FormDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDefinitionResponse.ProtoReflect.Descriptor instead.
func (*FormDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{5}
}

func (x *FormDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormDefinitionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FormDefinitionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormDefinitionResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FormDefinitionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FormDefinitionResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FormDefinitionResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *FormDefinitionResponse) GetUiSchema() string {
	if x != nil {
		return x.UiSchema
	}
	return ""
}

func (x *FormDefinitionResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FormDefinitionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FormDefinitionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// DeleteFormDefinitionResponse 删除表单定义响应
type DeleteFormDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormDefinitionResponse) Reset() {
	*x = DeleteFormDefinitionResponse{}
	mi := &file_api_form_v1_form_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormDefinitionResponse) ProtoMessage() {}

func (x *DeleteFormDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteFormDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFormDefinitionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListFormDefinitionsResponse 列出表单定义响应
type ListFormDefinitionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*FormDefinitionResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormDefinitionsResponse) Reset() {
	*x = ListFormDefinitionsResponse{}
	mi := &file_api_form_v1_form_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormDefinitionsResponse) ProtoMessage() {}

func (x *ListFormDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListFormDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{7}
}

func (x *ListFormDefinitionsResponse) GetItems() []*FormDefinitionResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFormDefinitionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SubmitFormDataRequest 提交表单数据请求
type SubmitFormDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFormDataRequest) Reset() {
	*x = SubmitFormDataRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFormDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFormDataRequest) ProtoMessage() {}

func (x *SubmitFormDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFormDataRequest.ProtoReflect.Descriptor instead.
func (*SubmitFormDataRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitFormDataRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *SubmitFormDataRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitFormDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitFormDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// GetFormDataRequest 获取表单数据请求
type GetFormDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormDataRequest) Reset() {
	*x = GetFormDataRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormDataRequest) ProtoMessage() {}

func (x *GetFormDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormDataRequest.ProtoReflect.Descriptor instead.
func (*GetFormDataRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{9}
}

func (x *GetFormDataRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *GetFormDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateFormDataRequest 更新表单数据请求
type UpdateFormDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormDataRequest) Reset() {
	*x = UpdateFormDataRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormDataRequest) ProtoMessage() {}

func (x *UpdateFormDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormDataRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateFormDataRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *UpdateFormDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFormDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// ListFormDataRequest 查询表单数据列表请求
type ListFormDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormDataRequest) Reset() {
	*x = ListFormDataRequest{}
	mi := &file_api_form_v1_form_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormDataRequest) ProtoMessage() {}

func (x *ListFormDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormDataRequest.ProtoReflect.Descriptor instead.
func (*ListFormDataRequest) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{11}
}

func (x *ListFormDataRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ListFormDataRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListFormDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFormDataRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// FormDataResponse 表单数据响应
type FormDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FormId        string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormDataResponse) Reset() {
	*x = FormDataResponse{}
	mi := &file_api_form_v1_form_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDataResponse) ProtoMessage() {}

func (x *FormDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDataResponse.ProtoReflect.Descriptor instead.
func (*FormDataResponse) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{12}
}

func (x *FormDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormDataResponse) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *FormDataResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FormDataResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FormDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *FormDataResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FormDataResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ListFormDataResponse 查询表单数据列表响应
type ListFormDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FormDataResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormDataResponse) Reset() {
	*x = ListFormDataResponse{}
	mi := &file_api_form_v1_form_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormDataResponse) ProtoMessage() {}

func (x *ListFormDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_form_v1_form_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormDataResponse.ProtoReflect.Descriptor instead.
func (*ListFormDataResponse) Descriptor() ([]byte, []int) {
	return file_api_form_v1_form_proto_rawDescGZIP(), []int{13}
}

func (x *ListFormDataResponse) GetItems() []*FormDataResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFormDataResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_form_v1_form_proto protoreflect.FileDescriptor

const file_api_form_v1_form_proto_rawDesc = "" +
	"\n" +
	"\x16api/form/v1/form.proto\x12\vapi.form.v1\x1a\x1cgoogle/api/annotations.proto\"\xd5\x01\n" +
	"\x1bCreateFormDefinitionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06schema\x18\x06 \x01(\tR\x06schema\x12\x1b\n" +
	"\tui_schema\x18\a \x01(\tR\buiSchema\"*\n" +
	"\x18GetFormDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x1bUpdateFormDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema\x12\x1b\n" +
	"\tui_schema\x18\x05 \x01(\tR\buiSchema\"-\n" +
	"\x1bDeleteFormDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x1aListFormDefinitionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xb8\x02\n" +
	"\x16FormDefinitionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06schema\x18\a \x01(\tR\x06schema\x12\x1b\n" +
	"\tui_schema\x18\b \x01(\tR\buiSchema\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"8\n" +
	"\x1cDeleteFormDefinitionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"n\n" +
	"\x1bListFormDefinitionsResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.api.form.v1.FormDefinitionResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"z\n" +
	"\x15SubmitFormDataRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"=\n" +
	"\x12GetFormDataRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"T\n" +
	"\x15UpdateFormDataRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"|\n" +
	"\x13ListFormDataRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc3\x01\n" +
	"\x10FormDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"a\n" +
	"\x14ListFormDataResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.api.form.v1.FormDataResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xa7\x05\n" +
	"\x15FormDefinitionService\x12\x7f\n" +
	"\x14CreateFormDefinition\x12(.api.form.v1.CreateFormDefinitionRequest\x1a#.api.form.v1.FormDefinitionResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/forms\x12{\n" +
	"\x11GetFormDefinition\x12%.api.form.v1.GetFormDefinitionRequest\x1a#.api.form.v1.FormDefinitionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/forms/{id}\x12\x84\x01\n" +
	"\x14UpdateFormDefinition\x12(.api.form.v1.UpdateFormDefinitionRequest\x1a#.api.form.v1.FormDefinitionResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/forms/{id}\x12\x87\x01\n" +
	"\x14DeleteFormDefinition\x12(.api.form.v1.DeleteFormDefinitionRequest\x1a).api.form.v1.DeleteFormDefinitionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/forms/{id}\x12\x7f\n" +
	"\x13ListFormDefinitions\x12'.api.form.v1.ListFormDefinitionsRequest\x1a(.api.form.v1.ListFormDefinitionsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/forms2\x88\x04\n" +
	"\x0fFormDataService\x12|\n" +
	"\x0eSubmitFormData\x12\".api.form.v1.SubmitFormDataRequest\x1a\x1d.api.form.v1.FormDataResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/forms/{form_id}/data\x12x\n" +
	"\vGetFormData\x12\x1f.api.form.v1.GetFormDataRequest\x1a\x1d.api.form.v1.FormDataResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/forms/{form_id}/data/{id}\x12\x81\x01\n" +
	"\x0eUpdateFormData\x12\".api.form.v1.UpdateFormDataRequest\x1a\x1d.api.form.v1.FormDataResponse\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/forms/{form_id}/data/{id}\x12y\n" +
	"\fListFormData\x12 .api.form.v1.ListFormDataRequest\x1a!.api.form.v1.ListFormDataResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/forms/{form_id}/dataB\xa2\x01\n" +
	"\x0fcom.api.form.v1B\tFormProtoP\x01Z6github.com/lk2023060901/go-next-erp/api/form/v1;formv1\xa2\x02\x03AFX\xaa\x02\vApi.Form.V1\xca\x02\vApi\\Form\\V1\xe2\x02\x17Api\\Form\\V1\\GPBMetadata\xea\x02\rApi::Form::V1b\x06proto3"

var (
	file_api_form_v1_form_proto_rawDescOnce sync.Once
	file_api_form_v1_form_proto_rawDescData []byte
)

func file_api_form_v1_form_proto_rawDescGZIP() []byte {
	file_api_form_v1_form_proto_rawDescOnce.Do(func() {
		file_api_form_v1_form_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_form_v1_form_proto_rawDesc), len(file_api_form_v1_form_proto_rawDesc)))
	})
	return file_api_form_v1_form_proto_rawDescData
}

var file_api_form_v1_form_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_form_v1_form_proto_goTypes = []any{
	(*CreateFormDefinitionRequest)(nil),  // 0: api.form.v1.CreateFormDefinitionRequest
	(*GetFormDefinitionRequest)(nil),     // 1: api.form.v1.GetFormDefinitionRequest
	(*UpdateFormDefinitionRequest)(nil),  // 2: api.form.v1.UpdateFormDefinitionRequest
	(*DeleteFormDefinitionRequest)(nil),  // 3: api.form.v1.DeleteFormDefinitionRequest
	(*ListFormDefinitionsRequest)(nil),   // 4: api.form.v1.ListFormDefinitionsRequest
	(*FormDefinitionResponse)(nil),       // 5: api.form.v1.FormDefinitionResponse
	(*DeleteFormDefinitionResponse)(nil), // 6: api.form.v1.DeleteFormDefinitionResponse
	(*ListFormDefinitionsResponse)(nil),  // 7: api.form.v1.ListFormDefinitionsResponse
	(*SubmitFormDataRequest)(nil),        // 8: api.form.v1.SubmitFormDataRequest
	(*GetFormDataRequest)(nil),           // 9: api.form.v1.GetFormDataRequest
	(*UpdateFormDataRequest)(nil),        // 10: api.form.v1.UpdateFormDataRequest
	(*ListFormDataRequest)(nil),          // 11: api.form.v1.ListFormDataRequest
	(*FormDataResponse)(nil),             // 12: api.form.v1.FormDataResponse
	(*ListFormDataResponse)(nil),         // 13: api.form.v1.ListFormDataResponse
}
var file_api_form_v1_form_proto_depIdxs = []int32{
	5,  // 0: api.form.v1.ListFormDefinitionsResponse.items:type_name -> api.form.v1.FormDefinitionResponse
	12, // 1: api.form.v1.ListFormDataResponse.items:type_name -> api.form.v1.FormDataResponse
	0,  // 2: api.form.v1.FormDefinitionService.CreateFormDefinition:input_type -> api.form.v1.CreateFormDefinitionRequest
	1,  // 3: api.form.v1.FormDefinitionService.GetFormDefinition:input_type -> api.form.v1.GetFormDefinitionRequest
	2,  // 4: api.form.v1.FormDefinitionService.UpdateFormDefinition:input_type -> api.form.v1.UpdateFormDefinitionRequest
	3,  // 5: api.form.v1.FormDefinitionService.DeleteFormDefinition:input_type -> api.form.v1.DeleteFormDefinitionRequest
	4,  // 6: api.form.v1.FormDefinitionService.ListFormDefinitions:input_type -> api.form.v1.ListFormDefinitionsRequest
	8,  // 7: api.form.v1.FormDataService.SubmitFormData:input_type -> api.form.v1.SubmitFormDataRequest
	9,  // 8: api.form.v1.FormDataService.GetFormData:input_type -> api.form.v1.GetFormDataRequest
	10, // 9: api.form.v1.FormDataService.UpdateFormData:input_type -> api.form.v1.UpdateFormDataRequest
	11, // 10: api.form.v1.FormDataService.ListFormData:input_type -> api.form.v1.ListFormDataRequest
	5,  // 11: api.form.v1.FormDefinitionService.CreateFormDefinition:output_type -> api.form.v1.FormDefinitionResponse
	5,  // 12: api.form.v1.FormDefinitionService.GetFormDefinition:output_type -> api.form.v1.FormDefinitionResponse
	5,  // 13: api.form.v1.FormDefinitionService.UpdateFormDefinition:output_type -> api.form.v1.FormDefinitionResponse
	6,  // 14: api.form.v1.FormDefinitionService.DeleteFormDefinition:output_type -> api.form.v1.DeleteFormDefinitionResponse
	7,  // 15: api.form.v1.FormDefinitionService.ListFormDefinitions:output_type -> api.form.v1.ListFormDefinitionsResponse
	12, // 16: api.form.v1.FormDataService.SubmitFormData:output_type -> api.form.v1.FormDataResponse
	12, // 17: api.form.v1.FormDataService.GetFormData:output_type -> api.form.v1.FormDataResponse
	12, // 18: api.form.v1.FormDataService.UpdateFormData:output_type -> api.form.v1.FormDataResponse
	13, // 19: api.form.v1.FormDataService.ListFormData:output_type -> api.form.v1.ListFormDataResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_form_v1_form_proto_init() }
func file_api_form_v1_form_proto_init() {
	if File_api_form_v1_form_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_form_v1_form_proto_rawDesc), len(file_api_form_v1_form_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_form_v1_form_proto_goTypes,
		DependencyIndexes: file_api_form_v1_form_proto_depIdxs,
		MessageInfos:      file_api_form_v1_form_proto_msgTypes,
	}.Build()
	File_api_form_v1_form_proto = out.File
	file_api_form_v1_form_proto_goTypes = nil
	file_api_form_v1_form_proto_depIdxs = nil
}
