// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/auth/v1/user.proto

package authv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户列表请求
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`       // 分页参数
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"` // 快速搜索（username/email）
	Filters       []*FilterGroup         `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"` // 高级筛选条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListUsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListUsersRequest) GetFilters() []*FilterGroup {
	if x != nil {
		return x.Filters
	}
	return nil
}

// 用户列表响应
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// 获取用户请求
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 更新用户请求
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // active/inactive/locked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 删除用户请求
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 分配角色请求
type AssignRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesRequest) Reset() {
	*x = AssignRolesRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesRequest) ProtoMessage() {}

func (x *AssignRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *AssignRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRolesRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 获取用户角色请求
type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取用户角色响应
type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 获取用户会话请求
type GetUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionsRequest) Reset() {
	*x = GetUserSessionsRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionsRequest) ProtoMessage() {}

func (x *GetUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 会话信息
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_auth_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// 获取用户会话响应
type GetUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionsResponse) Reset() {
	*x = GetUserSessionsResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionsResponse) ProtoMessage() {}

func (x *GetUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// 获取用户权限请求
type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取用户权限响应
type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_api_auth_v1_user_proto protoreflect.FileDescriptor

const file_api_auth_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/auth/v1/user.proto\x12\vapi.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x18api/auth/v1/common.proto\"\x8e\x01\n" +
	"\x10ListUsersRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.api.auth.v1.PageRequestR\x04page\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x122\n" +
	"\afilters\x18\x03 \x03(\v2\x18.api.auth.v1.FilterGroupR\afilters\"o\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.api.auth.v1.UserInfoR\x05users\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.api.auth.v1.PageResponseR\x04page\"*\n" +
	"\x0eGetUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"d\n" +
	"\x11UpdateUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"-\n" +
	"\x11DeleteUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"R\n" +
	"\x12AssignRolesRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"8\n" +
	"\x13GetUserRolesRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"C\n" +
	"\x14GetUserRolesResponse\x12+\n" +
	"\x05roles\x18\x01 \x03(\v2\x15.api.auth.v1.RoleInfoR\x05roles\";\n" +
	"\x16GetUserSessionsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"\x99\x01\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"O\n" +
	"\x17GetUserSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.api.auth.v1.SessionInfoR\bsessions\">\n" +
	"\x19GetUserPermissionsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"[\n" +
	"\x1aGetUserPermissionsResponse\x12=\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1b.api.auth.v1.PermissionInfoR\vpermissions2\x9d\a\n" +
	"\vUserService\x12a\n" +
	"\tListUsers\x12\x1d.api.auth.v1.ListUsersRequest\x1a\x1e.api.auth.v1.ListUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12Y\n" +
	"\aGetUser\x12\x1b.api.auth.v1.GetUserRequest\x1a\x15.api.auth.v1.UserInfo\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12b\n" +
	"\n" +
	"UpdateUser\x12\x1e.api.auth.v1.UpdateUserRequest\x1a\x15.api.auth.v1.UserInfo\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/users/{id}\x12`\n" +
	"\n" +
	"DeleteUser\x12\x1e.api.auth.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12p\n" +
	"\vAssignRoles\x12\x1f.api.auth.v1.AssignRolesRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/users/{user_id}/roles\x12z\n" +
	"\fGetUserRoles\x12 .api.auth.v1.GetUserRolesRequest\x1a!.api.auth.v1.GetUserRolesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/users/{user_id}/roles\x12\x86\x01\n" +
	"\x0fGetUserSessions\x12#.api.auth.v1.GetUserSessionsRequest\x1a$.api.auth.v1.GetUserSessionsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/users/{user_id}/sessions\x12\x92\x01\n" +
	"\x12GetUserPermissions\x12&.api.auth.v1.GetUserPermissionsRequest\x1a'.api.auth.v1.GetUserPermissionsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/users/{user_id}/permissionsB\xa2\x01\n" +
	"\x0fcom.api.auth.v1B\tUserProtoP\x01Z6github.com/lk2023060901/go-next-erp/api/auth/v1;authv1\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var (
	file_api_auth_v1_user_proto_rawDescOnce sync.Once
	file_api_auth_v1_user_proto_rawDescData []byte
)

func file_api_auth_v1_user_proto_rawDescGZIP() []byte {
	file_api_auth_v1_user_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_user_proto_rawDesc), len(file_api_auth_v1_user_proto_rawDesc)))
	})
	return file_api_auth_v1_user_proto_rawDescData
}

var file_api_auth_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_auth_v1_user_proto_goTypes = []any{
	(*ListUsersRequest)(nil),           // 0: api.auth.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 1: api.auth.v1.ListUsersResponse
	(*GetUserRequest)(nil),             // 2: api.auth.v1.GetUserRequest
	(*UpdateUserRequest)(nil),          // 3: api.auth.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),          // 4: api.auth.v1.DeleteUserRequest
	(*AssignRolesRequest)(nil),         // 5: api.auth.v1.AssignRolesRequest
	(*GetUserRolesRequest)(nil),        // 6: api.auth.v1.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),       // 7: api.auth.v1.GetUserRolesResponse
	(*GetUserSessionsRequest)(nil),     // 8: api.auth.v1.GetUserSessionsRequest
	(*SessionInfo)(nil),                // 9: api.auth.v1.SessionInfo
	(*GetUserSessionsResponse)(nil),    // 10: api.auth.v1.GetUserSessionsResponse
	(*GetUserPermissionsRequest)(nil),  // 11: api.auth.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 12: api.auth.v1.GetUserPermissionsResponse
	(*PageRequest)(nil),                // 13: api.auth.v1.PageRequest
	(*FilterGroup)(nil),                // 14: api.auth.v1.FilterGroup
	(*UserInfo)(nil),                   // 15: api.auth.v1.UserInfo
	(*PageResponse)(nil),               // 16: api.auth.v1.PageResponse
	(*RoleInfo)(nil),                   // 17: api.auth.v1.RoleInfo
	(*PermissionInfo)(nil),             // 18: api.auth.v1.PermissionInfo
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
}
var file_api_auth_v1_user_proto_depIdxs = []int32{
	13, // 0: api.auth.v1.ListUsersRequest.page:type_name -> api.auth.v1.PageRequest
	14, // 1: api.auth.v1.ListUsersRequest.filters:type_name -> api.auth.v1.FilterGroup
	15, // 2: api.auth.v1.ListUsersResponse.users:type_name -> api.auth.v1.UserInfo
	16, // 3: api.auth.v1.ListUsersResponse.page:type_name -> api.auth.v1.PageResponse
	17, // 4: api.auth.v1.GetUserRolesResponse.roles:type_name -> api.auth.v1.RoleInfo
	9,  // 5: api.auth.v1.GetUserSessionsResponse.sessions:type_name -> api.auth.v1.SessionInfo
	18, // 6: api.auth.v1.GetUserPermissionsResponse.permissions:type_name -> api.auth.v1.PermissionInfo
	0,  // 7: api.auth.v1.UserService.ListUsers:input_type -> api.auth.v1.ListUsersRequest
	2,  // 8: api.auth.v1.UserService.GetUser:input_type -> api.auth.v1.GetUserRequest
	3,  // 9: api.auth.v1.UserService.UpdateUser:input_type -> api.auth.v1.UpdateUserRequest
	4,  // 10: api.auth.v1.UserService.DeleteUser:input_type -> api.auth.v1.DeleteUserRequest
	5,  // 11: api.auth.v1.UserService.AssignRoles:input_type -> api.auth.v1.AssignRolesRequest
	6,  // 12: api.auth.v1.UserService.GetUserRoles:input_type -> api.auth.v1.GetUserRolesRequest
	8,  // 13: api.auth.v1.UserService.GetUserSessions:input_type -> api.auth.v1.GetUserSessionsRequest
	11, // 14: api.auth.v1.UserService.GetUserPermissions:input_type -> api.auth.v1.GetUserPermissionsRequest
	1,  // 15: api.auth.v1.UserService.ListUsers:output_type -> api.auth.v1.ListUsersResponse
	15, // 16: api.auth.v1.UserService.GetUser:output_type -> api.auth.v1.UserInfo
	15, // 17: api.auth.v1.UserService.UpdateUser:output_type -> api.auth.v1.UserInfo
	19, // 18: api.auth.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	19, // 19: api.auth.v1.UserService.AssignRoles:output_type -> google.protobuf.Empty
	7,  // 20: api.auth.v1.UserService.GetUserRoles:output_type -> api.auth.v1.GetUserRolesResponse
	10, // 21: api.auth.v1.UserService.GetUserSessions:output_type -> api.auth.v1.GetUserSessionsResponse
	12, // 22: api.auth.v1.UserService.GetUserPermissions:output_type -> api.auth.v1.GetUserPermissionsResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_auth_v1_user_proto_init() }
func file_api_auth_v1_user_proto_init() {
	if File_api_auth_v1_user_proto != nil {
		return
	}
	file_api_auth_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_user_proto_rawDesc), len(file_api_auth_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_user_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_user_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_user_proto_msgTypes,
	}.Build()
	File_api_auth_v1_user_proto = out.File
	file_api_auth_v1_user_proto_goTypes = nil
	file_api_auth_v1_user_proto_depIdxs = nil
}
